# Generated by Django 5.2.17 on 2026-09-26 12:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_sku_sales_and_bank_tallies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banktally',
            constraint=models.CheckConstraint(condition=models.Q(('statement_credits__gte', 0)), name='bank_tally_credits_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='banktally',
            constraint=models.CheckConstraint(condition=models.Q(('statement_debits__gte', 0)), name='bank_tally_debits_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('sales_amount__isnull', True), ('kind', 'sold'), _connector='OR'), name='stock_sales_amount_only_for_sales'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('sales_amount__isnull', True), ('sales_amount__gte', Decimal('0.01')), _connector='OR'), name='stock_sales_amount_positive'),
        ),
    ]
