# Generated by Django 5.2.17 on 2026-09-29 03:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_sales_tally_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_cost_behavior',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('special', 'Special'), ('tax', 'Tax'), ('inventory', 'Inventory cost')], default='variable', max_length=12),
        ),
        migrations.AddField(
            model_name='entry',
            name='capitalized_inventory_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='sale_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(db_index=True)),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('manufacturing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('extra_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_direct_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('batch_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='tracker.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='inventory_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='tracker.inventorylot'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='inventory_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='tracker.inventorylot'),
        ),
        migrations.CreateModel(
            name='LotDepletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depletions', to='tracker.inventorylot')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_depletions', to='tracker.stockmovement')),
            ],
            options={
                'ordering': ['lot__received_date', 'lot_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='lot_depletion_positive_qty')],
            },
        ),
    ]
