# Generated by Django 5.2.17 on 2026-09-29 03:27

from django.db import migrations, models


def backfill_legacy_lots(apps, schema_editor):
    Entry = apps.get_model("tracker", "Entry")
    Product = apps.get_model("tracker", "Product")
    InventoryLot = apps.get_model("tracker", "InventoryLot")
    StockMovement = apps.get_model("tracker", "StockMovement")
    LotDepletion = apps.get_model("tracker", "LotDepletion")
    Entry.objects.filter(kind="income", sale_date__isnull=True).update(sale_date=models.F("date"))
    for product in Product.objects.all().iterator():
        lots = []
        remaining = {}
        movements = StockMovement.objects.filter(product_id=product.pk, reversal__isnull=True).order_by("date", "pk")
        for movement in movements:
            if movement.kind in ("received", "returned", "adjust_in"):
                lot = InventoryLot.objects.create(owner_id=product.owner_id, product_id=product.pk,
                    received_date=movement.date, quantity_received=movement.quantity,
                    batch_name=movement.batch_name or "Legacy stock", costs_confirmed=False)
                movement.inventory_lot_id = lot.pk
                movement.save(update_fields=["inventory_lot"])
                lots.append(lot)
                remaining[lot.pk] = movement.quantity
            elif movement.kind == "sold":
                needed = movement.quantity
                for lot in lots:
                    qty = min(needed, remaining.get(lot.pk, 0))
                    if qty:
                        LotDepletion.objects.create(movement_id=movement.pk, lot_id=lot.pk,
                            quantity=qty, unit_cost=0)
                        remaining[lot.pk] -= qty
                        needed -= qty
                    if not needed:
                        break
            elif movement.kind in ("damaged", "adjust_out"):
                needed = movement.quantity
                for lot in lots:
                    qty = min(needed, remaining.get(lot.pk, 0))
                    remaining[lot.pk] -= qty
                    needed -= qty
                    if not needed:
                        break


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_category_default_cost_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='costs_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lotdepletion',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.RunPython(backfill_legacy_lots, migrations.RunPython.noop),
    ]
