# Generated by Django 5.2.17 on 2026-09-29 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_inventorylot_costs_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cost_behavior',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('special', 'Special'), ('tax', 'Tax'), ('inventory', 'Inventory cost')], default='variable', max_length=12),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_cost_behavior', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('special', 'Special'), ('tax', 'Tax'), ('inventory', 'Inventory cost')], default='variable', max_length=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='tracker.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tracker.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('owner', 'category', 'name'), name='unique_owner_category_subcategory'),
        ),
    ]
