# Generated by Django 5.2.17 on 2026-09-29 03:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_entry_cost_behavior_subcategory_entry_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='recognized_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Recognized sales amount'),
        ),
    ]
