# Generated by Django 5.2.17 on 2026-09-29 04:06

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_entry_recognized_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylot',
            name='base_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='extra_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='other_direct_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='lotdepletion',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='inventory_lot_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturing_cost__gte', 0)), name='inventory_lot_mfg_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('base_shipping_cost__gte', 0)), name='inventory_lot_base_ship_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('extra_shipping_cost__gte', 0)), name='inventory_lot_extra_ship_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('other_direct_cost__gte', 0)), name='inventory_lot_other_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lotdepletion',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='lot_depletion_nonnegative_cost'),
        ),
    ]
