# Generated by Django 5.2.17 on 2026-10-04 18:11

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_inventorylot_base_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=tracker.models.product_photo_path),
        ),
    ]
