# Generated by Django 5.2.17 on 2026-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_allow_empty_audit_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
            ],
        ),
    ]
